### PR TITLE
Misc. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
+ Some user-facing fixes
+ source comment fixes
+ removed double-whitespace in code comments

Typos discovered downstream in inkscape/inkscape

### CODE REVIEW

**Comment by luzpaz** [comment]
@tweenk care to review this PR ?

**Comment by luzpaz** [comment]
@caryoscelus care to merge this? No rush, just don't want to see it rot.

**Comment by caryoscelus** [comment]
@luzpaz i don't have push access here, but [merged into my fork](https://github.com/caryoscelus/lib2geom/commit/cf4bfc27def5f78636fb2b8d71ba4a0dcf306f59). Thx for the fixes ;)

**Comment by luzpaz** [comment]
> but merged into my fork. 

@caryoscelus does that means i can close this PR ?

**Comment by caryoscelus** [comment]
@luzpaz i'd leave it open; i think we can still hope inkscape developers will eventually get to review and merge it into upstream (i.e. here).

**Comment by luzpaz** [comment]
Thanks!

**Pull request merged**
